import type { DemoMailbox } from "./types.js";

export const demoMailboxes: DemoMailbox[] = [
  {
    mailbox_id: "mbx_atlas_demo",
    display_name: "Atlas — Demo",
    mailbox_email: "operator@atlas.synthetic.invalid",
    brand: "BUSINESS",
    purpose: "Synthetic partner correspondence",
    folders: ["INBOX", "Sent", "Archive"],
    messages: [
      {
        stable_message_id: "msg_atlas_001",
        mailbox_id: "mbx_atlas_demo",
        folder: "INBOX",
        from: [{ name: "Northwind Demo", address: "partner@northwind.synthetic.invalid" }],
        to: [{ address: "operator@atlas.synthetic.invalid" }],
        cc: [],
        subject: "Re: ATLAS — partnership proposal",
        received_at: "2026-08-20T09:40:00.000Z",
        unread: true,
        text_body: "Synthetic reply confirming the next review meeting for the ATLAS project.",
        message_id: "<atlas-001@synthetic.invalid>",
        in_reply_to: "<atlas-root@synthetic.invalid>",
        references: ["<atlas-root@synthetic.invalid>"],
        attachments: [
          {
            attachment_id: "att_atlas_brief",
            filename: "atlas-brief.txt",
            mime_type: "text/plain",
            content: "Synthetic ATLAS project brief. No real mailbox data is included.",
          },
        ],
      },
      {
        stable_message_id: "msg_atlas_002",
        mailbox_id: "mbx_atlas_demo",
        folder: "Sent",
        from: [{ address: "operator@atlas.synthetic.invalid" }],
        to: [{ name: "Northwind Demo", address: "partner@northwind.synthetic.invalid" }],
        cc: [],
        subject: "ATLAS — partnership proposal",
        received_at: "2026-08-19T14:10:00.000Z",
        unread: false,
        text_body: "Synthetic outbound context used only to demonstrate thread reconstruction.",
        message_id: "<atlas-root@synthetic.invalid>",
        in_reply_to: null,
        references: [],
        attachments: [],
      },
      {
        stable_message_id: "msg_atlas_003",
        mailbox_id: "mbx_atlas_demo",
        folder: "Archive",
        from: [{ name: "Compliance Demo", address: "review@compliance.synthetic.invalid" }],
        to: [{ address: "operator@atlas.synthetic.invalid" }],
        cc: [],
        subject: "Quarterly compliance summary",
        received_at: "2026-08-02T08:00:00.000Z",
        unread: false,
        text_body: "Synthetic archived compliance summary for search demonstrations.",
        message_id: "<compliance-003@synthetic.invalid>",
        in_reply_to: null,
        references: [],
        attachments: [],
      },
    ],
  },
  {
    mailbox_id: "mbx_orbit_demo",
    display_name: "Orbit — Demo",
    mailbox_email: "hello@orbit.synthetic.invalid",
    brand: "PERSONAL",
    purpose: "Synthetic customer correspondence",
    folders: ["INBOX", "Archive"],
    messages: [
      {
        stable_message_id: "msg_orbit_001",
        mailbox_id: "mbx_orbit_demo",
        folder: "INBOX",
        from: [{ name: "Customer Demo", address: "customer@sample.synthetic.invalid" }],
        to: [{ address: "hello@orbit.synthetic.invalid" }],
        cc: [],
        subject: "Product feedback — read-only workflow",
        received_at: "2026-08-21T11:22:00.000Z",
        unread: true,
        text_body: "Synthetic feedback praising a workflow that never changes mailbox state.",
        message_id: "<orbit-feedback@synthetic.invalid>",
        in_reply_to: null,
        references: [],
        attachments: [],
      },
      {
        stable_message_id: "msg_orbit_002",
        mailbox_id: "mbx_orbit_demo",
        folder: "Archive",
        from: [{ name: "Research Demo", address: "research@sample.synthetic.invalid" }],
        to: [{ address: "hello@orbit.synthetic.invalid" }],
        cc: [{ address: "archive@orbit.synthetic.invalid" }],
        subject: "MCP Apps interoperability notes",
        received_at: "2026-07-30T10:15:00.000Z",
        unread: false,
        text_body: "Synthetic notes about portable MCP Apps UI and standard search/fetch contracts.",
        message_id: "<orbit-mcp@synthetic.invalid>",
        in_reply_to: null,
        references: [],
        attachments: [],
      },
    ],
  },
];
